version: "3.9"

services:
  localstack:
      image: localstack/localstack
      container_name: localstack
      ports:
       - "4566:4566"
       - "9001:9000"
      environment:
       - SERVICES=dynamodb,iam
       - DEBUG=1
       - AWS_ACCESS_KEY_ID=xxx
       - AWS_SECRET_ACCESS_KEY=xxx
       - DEFAULT_REGION=eu-west-1
       - PORT_WEB_UI=9000
       - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
       - overlay
  
  dynamodb-admin:
      image:  aaronshaf/dynamodb-admin
      container_name: dynamodb-admin
      ports:
        - "8001:8001"
      environment:
        - AWS_ACCESS_KEY_ID=xxx
        - AWS_SECRET_KEY=xxx
        - AWS_DEFAULT_REGION=eu-west-1
        - "DYNAMO_ENDPOINT=http://localstack:4566"
      networks:
        - overlay
  
  todo-api:
      build: .
      ports:
        - "8080:80"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - AWS_ACCESS_KEY_ID=xxx
        - AWS_SECRET_KEY=xxx
        - AWS_DEFAULT_REGION=eu-west-1
      networks:
        - overlay

networks:
  overlay: